build.gradle.kts, src/main/java/org/nexters/jaknaeso/common/log/P6SpyConfig.java, src/main/java/org/nexters/jaknaeso/common/log/P6SpyFormatter.java, src/main/resources/application-dev.yaml, src/main/resources/application-local.yaml, src/main/resources/log/log4j2-dev.yml, src/main/resources/log/log4j2-local.yml, src/main/resources/log4jdbc.log4j2.properties, src/main/resources/spy.properties
어플리케이션 로깅을 위해 log4j2를 이용하여 로깅을 구현하였습니다. 
각 개발 환경에 맞게 로깅을 다르게 할 수 있도록 분리하였습니다.
아주아주 기본적인거만 만들어서 무슨무슨 작업들이 더 필요할 지 아직 감이 안와서 롤링파일과 콘솔만 작성하였습니다.
ELK를 붙이는것도 인프라 비용이라 일단 사용하지는 않았고, ELK 필요시 작업 하도록 하겠습니다.
로깅 설정에 정확히 어떤 정보들이 필요한 지 잘 몰라서 아주 기본적인 부분만 해두어서 추가 필요한 내용 알려주시면 추가 작업하겠습니다.
=> FEAT(#1): 로깅 기본 설정

.github/workflows/cd.yml, .github/workflows/deploy-swagger-ui.yaml, .github/workflows/terraform.yml, terraform/main.tf, terraform/modules/network/variables.tf, terraform/modules/server/variables.tf, terraform/variables.tf
테라폼 워크플로우와 CD 파이프라인을 수정하였습니다.
- 테라폼 admin ip 추가
- cd 파이프라인 동작 시 securitygroup에 대한 정보가 노출되어서 안보이도록 수정
=> Fix(#11): 워크플로우 이슈 해결

.github/workflows/cd.yml, docker-compose.yml, nginx/default.conf, terraform/modules/server/network.tf
도메인 이름 설정을 위한 작업을 진행했습니다.
- 도메인 생성 `dev.jaknaeso.kro.kr`
- nginx 설정 파일 추가
- 도커 컴포즈에 nginx 컨테이너 추가
- cd 워크플로우에 nginx 설정 파일 복사 및 재시작 명령어 추가
- ncp acg 에서 80번 포트 인바운드 규칙 추가
- 인바운드 규칙에 8080번만 열어놓으셨는데 80번에 대해 다 열어줘도 괜찮을까요?
- 호스트랑 직접 매핑할 필요가 없다면 nginx 컨테이너도 같은 네트워크를 공유하니까 server 컨테이너도 expose 사용해도 될 것 같습니다
- 지금은 ncp에 직접 접속해서 바꾸었습니다. 변경하게 된다면 테라폼 코드도 변경하도록 하겠습니다!
+) `내도메인` 사용했습니다. 스프레드 시트에 계정 정보 추가해두었습니다.
=> Feat(#19): domain name 적용

.github/workflows/ci.yml, docker-compose.yml, jaknaeso-core/src/main/resources/log/log4j2-dev.yml, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/JaknaesoserverApplicationTest.java
CI에서 아무 작업도 진행하지 않아서 Test가 제대로 진행되는지 확인이 불가했습니다. 테스트에서 문제가 발생하면 배포에 문제가 생기기때문에 PR이 열릴 때 테스트작업 진행하도록 하였습니다.
로그도 마운트하도록 변경하였습니다.
- CI 테스트 추가
- 로그 마운트 (/var/log/jaknaeso 에 저장하도록 하였습니다)
- contextload를 disabled해두었습니다.
=> Feat(#29) ci test flow 추가

.github/workflows/ci.yml, docker-compose.yml, jaknaeso-core/src/main/resources/log/log4j2-dev.yml, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/config/WebMvcConfig.java, terraform/modules/server/network.tf
- cors 추가
- db expose -> port로 변경
프론트에서 작업 가능하게 로컬호스트와 배포url을 cors설정에 추가하였습니다.
db에 접근 가능하게 expose에서 port로 변경하고, 3306 포트를 ssh 접속가능한 ip들과 같이 설정하였습니다.
=> Fix(#40) cors 에러 수정

.github/workflows/cd.yml, .github/workflows/ci.yml, docker-compose.yml, jaknaeso-core/src/main/resources/log/log4j2-dev.yml, jaknaeso-server/Dockerfile
- docker-compose volume 마운트 오류 해결
docker-compose 볼륨 마운트 설정이 잘못되어있어서 수정하였습니다.
그리고 로그가 안남아서 확인해보니 profile설정이 제대로 안되고있어서 변경했습니다.
=> Fix(#44): compose 오류 해결

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/dto/SurveyHistoryDetailResponse.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/dto/SurveyHistoryResponse.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/dto/SurveySubmissionCommand.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/SurveySubmission.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/model/SurveySubmissionTest.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/repository/SurveyBundleRepositoryTest.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/service/SurveyServiceTest.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/survey/controller/SurveyController.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/survey/controller/dto/SurveySubmissionRequest.java, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/survey/controller/SurveyControllerTest.java
일단위로 제출 할 수 있는지 여부 판단하도록 하였습니다.
- 일단위 제출 여부 판단 로직 추가
뭔가 잘 바꿔보려고 했는데.. 좋은 생각이 안떠오르네요 그래서 중복된 코드가 조금 들어가있습니다.
그리고 새로운 클래스 만들어서 작성하거나 해도 좋을 것 같긴한데 추후에 리팩토링 고민해보겠습닌다 ㅠㅠ
=> Fix(#56) 일단위로 제출로 변경

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/common/support/error/CustomException.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/common/support/error/ErrorType.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/common/controller/ApiControllerAdvice.java
- 번들 예외 발생시 500에러 발생
- 번들 예외 커스텀 예외로 변경
에러 로그 보고 추가적으로 예외처리 하면 좋을 것 같아서 아래 예외 처리 추가했습니다.
- NoResourceFoundException 처리
- MethodArgumentTypeMismatchException 처리
=> Fix(#73): 번들 커스텀 예외 처리

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/SurveyRecord.java, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/survey/controller/SurveyControllerTest.java
설문 결과 데이터 조회 필드 추가
설문 결과 조회 응답에 제출 아이디를 추가하였습니다.
=> Feat(#80): 설문결과 조회 필드 추가

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/dto/SurveyHistoryDetailResponse.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/service/SurveyServiceTest.java, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/survey/controller/SurveyControllerTest.java
회차 정보를 추가하였습니다.
- 회차 정보를 추가하기 위해 AtomicInteger를 통한 스트림내부 인덱스 계산하였습니다.
=> Feat(#84): 회차 정보 추가

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/model/Character.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/dto/SurveyHistoryResponse.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/service/SurveyServiceTest.java
- 온보딩 진행 하지 않아도 예외 발생하지 않도록 임시로 처리
- 온보딩 진행하지 않으면 번들id 1 내려주게 임시 하드코딩
- 온보딩 작업 완료되면 삭제
=> Feat(#86): 임시 온보딩 예외처리 무효화

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/auth/service/OauthService.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/member/model/Member.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/auth/service/OauthServiceIntegrationTest.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/member/model/MemberTest.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/service/SurveyServiceTest.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/auth/controller/AuthController.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/auth/dto/TokenResponse.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/auth/service/AuthFacadeService.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/auth/service/JwtService.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/auth/service/dto/LoginResponse.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/auth/service/dto/TokenResponse.java, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/auth/controller/AuthControllerTest.java
로그인 시 온보딩 여부 추가
로그인 이후에 온보딩에 대한 정보를 응답 할 수 있도록 추가하였습니다.
=> Feat(#94): 로그인시 온보딩 여부 추가

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/model/ValueCharacter.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/service/dto/CharacterResponse.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/character/service/CharacterServiceTest.java
키워드 넘기도록 변경했습니다.
필드에 `캐릭터 이름`을 넣어주고 있어서 키워드 넘기도록 변경
=> Feat(#93): 캐릭터 조회 dto 수정

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/SurveySubmission.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/model/SurveySubmissionTest.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/service/SurveyServiceTest.java
현재 온보딩 진행한 당일에는 다음 번들의 1회차 진행 불가하여 온보딩에 한하여 진행 가능하게 변경 
마지막 제출이 온보딩인 경우 다음 번들의 질문 가능하도록 구현
=> Feat(#98) 온보딩 진행해도 다음 번들 가능하도록 구현

jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/character/controller/CharacterControllerTest.java
누락된 api 문서 작성
- api 문서 identifier가 같아서 오버라이트한 문제여서 식별자를 다르게 작성
- api description 문맥에 맞게 변경
=> Test(#102): 누락된 api 문서 작성

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/model/CharacterRecord.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/service/dto/SimpleCharacterResponse.java
- 캐릭터 목록 조회 - isCompleted 버그 수정
=> Fix(#103): 캐릭터 목록 조회 - isCompleted 버그 수정

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/service/CharacterService.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/service/dto/CharacterResponse.java, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/character/controller/CharacterControllerTest.java
=> Feat(#111): 번들 아이디 추가

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/service/CharacterService.java
=> Fix(#115): 캐릭터 상세 조회 - 검색 조건 버그 수정

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/model/ValueReports.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/KeywordScoreNormalizer.java
=> Fix(#119): 가치관-분석-그래프-크기-문제

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/character/model/CharacterRecord.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/Survey.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/SurveyBundle.java
- soft delete를 정책으로 정해놓았기에 `orphanRemoval`를 사용해 hard delete를 하는 상황이 어색
- `orphanRemoval` 설정 제거
=> Fix(#126): orphanRemoval 설정 제거

jaknaeso-core/src/main/java/org/nexters/jaknaesocore/common/support/infrastructure/SystemLocalDateTimeHolder.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/common/support/service/LocalDateTimeHolder.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/member/model/Member.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/model/SurveySubmission.java, jaknaeso-core/src/main/java/org/nexters/jaknaesocore/domain/survey/service/SurveyService.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/common/support/mock/TestLocalDateTimeHolder.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/member/model/MemberTest.java, jaknaeso-core/src/test/java/org/nexters/jaknaesocore/domain/survey/service/SurveyServiceTest.java, jaknaeso-server/src/main/java/org/nexters/jaknaesoserver/domain/survey/controller/SurveyController.java, jaknaeso-server/src/test/java/org/nexters/jaknaesoserver/domain/survey/controller/SurveyControllerTest.java
시간에 대한 정보를 테스트하기 쉽게 인터페이스 사용하도록 하였습니다.
- Test시에는 고정된 시간을 사용할 수 있도록 TestTimeHolder를 이용하도록하였습니다.
=> Feat(#128): LocalDateTimeHolder 사용
